    kind: pipeline
    name: default

    steps:
    - name: docker
      image: plugins/docker
      context: .
      settings:
        repo: djpbessems/simpool
        tags: latest
        username:
          from_secret: dockerhub_username
        password:
          from_secret: dockerhub_password
